// Phase 24H conformance — type-only consumption end-to-end.
//
// This test exercises the type-only `@loa/straylight/host` package
// subpath through the package's `exports` map, NOT through a relative
// path. It builds declarations if missing, creates a temp consumer
// fixture, symlinks `node_modules/@loa/straylight` to the repo root,
// writes a fixture file that uses ONLY `import type` from
// `@loa/straylight/host` and `@loa/straylight`, and runs `tsc --noEmit`
// against the fixture under both `moduleResolution: "Bundler"` and
// `moduleResolution: "NodeNext"`.
//
// Phase 24H supported-consumer assumptions (SKP-001):
//   * TypeScript >= 5.4 (pinned via devDependencies).
//   * moduleResolution: "Bundler" or "NodeNext".
//   * `import type` only — runtime/value imports of @loa/straylight/host
//     are unsupported and expected to fail to resolve in Phase 24H.
//   * Older resolver modes ("node", "classic", "node10", "node16") are
//     NOT supported in Phase 24H.
//
// Pins:
//   * the package's TypeScript devDependency satisfies >= 5.4;
//   * `tsc --noEmit` against the fixture passes under both
//     moduleResolution modes (Bundler and NodeNext);
//   * the fixture compiles WITHOUT executing any runtime import; no
//     `await import('@loa/straylight/host')` call is made by the
//     positive-path fixture;
//   * the host barrel resolves through the package's `exports` map's
//     `./host` subpath under the `types` condition;
//   * dynamic ESM `import('@loa/straylight/host')` at runtime fails
//     intentionally (no runtime condition in `exports`);
//   * CJS `require('@loa/straylight/host')` at runtime fails
//     intentionally (no runtime condition in `exports`);
//   * the same failures hold for the root `@loa/straylight` subpath;
//   * an attempt to resolve the `./host` subpath under an unsupported
//     resolver mode (`moduleResolution: "node"`) does not resolve to
//     the host `.d.ts` (SKP-001 unsupported-resolver posture).
//
// This is the local end-to-end validation referenced by
// ADR-024G's Decision rule §10 (tag-/release-pinned consumption only)
// and ADR-024F §"Future Phase 24H entry conditions" §5 ("the
// follow-up implementation phase's PR includes at least one local
// validation that exercises the new `./host` subpath end-to-end").

import { execFileSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

const SUPPORTED_MODULE_RESOLUTIONS = ['Bundler', 'NodeNext'] as const;
type SupportedModuleResolution = typeof SUPPORTED_MODULE_RESOLUTIONS[number];

const MIN_TS_MAJOR = 5;
const MIN_TS_MINOR = 4;

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');

const WEDGE_DTS = resolve(ROOT, 'dist-types/src/straylight/index.d.ts');
const HOST_DTS = resolve(ROOT, 'dist-types/src/straylight/host/index.d.ts');
const TSC = resolve(ROOT, 'node_modules/.bin/tsc');

function buildDeclarationsIfMissing(): void {
  if (existsSync(WEDGE_DTS) && existsSync(HOST_DTS)) return;
  execFileSync('npm', ['run', 'build'], { cwd: ROOT, stdio: 'pipe' });
}

const FIXTURE_SOURCE = `// Phase 24H type-only consumption fixture.
//
// This file is generated by tests/phase-24h-type-only-consumption.test.ts.
// It exists only to feed \`tsc --noEmit\` a consumer that uses ONLY
// \`import type { ... }\` from \`@loa/straylight/host\` and
// \`@loa/straylight\`. There is no runtime import; nothing in this
// file is ever executed.

import type {
  IntakeDeps,
  ReceiptDeps,
  ProvenanceDeps,
  AuditLookupDeps,
  EstateSummaryDeps,
  TenantCheckResult,
  TenantResolver,
  IntakeDenyEntry,
  IntakeDenyLog,
} from '@loa/straylight/host';

import type {
  Actor,
  RecallRequest,
  RecallPack,
  RecallReceipt,
  AuditEvent,
} from '@loa/straylight';

// Reference each type at least once so tsc surfaces an unused-import
// error if the export ever drops.
export type ConsumerSurface = {
  intake: IntakeDeps;
  receipt: ReceiptDeps;
  provenance: ProvenanceDeps;
  auditLookup: AuditLookupDeps;
  estateSummary: EstateSummaryDeps;
  tenantCheck: TenantCheckResult;
  tenantResolver: TenantResolver;
  denyEntry: IntakeDenyEntry;
  denyLog: IntakeDenyLog;
  actor: Actor;
  request: RecallRequest;
  pack: RecallPack;
  receiptValue: RecallReceipt;
  audit: AuditEvent;
};
`;

interface FixtureContext {
  tempRoot: string;
  fixtureDir: string;
  consumerTsPath: string;
  nodeModulesDir: string;
  symlinkPath: string;
}

function setupFixture(): FixtureContext {
  const tempRoot = mkdtempSync(resolve(tmpdir(), 'phase-24h-consumer-'));
  const fixtureDir = resolve(tempRoot, 'consumer');
  const nodeModulesDir = resolve(fixtureDir, 'node_modules');
  const scopeDir = resolve(nodeModulesDir, '@loa');
  const symlinkPath = resolve(scopeDir, 'straylight');
  const consumerTsPath = resolve(fixtureDir, 'consumer.ts');

  mkdirSync(scopeDir, { recursive: true });
  symlinkSync(ROOT, symlinkPath, 'dir');
  writeFileSync(consumerTsPath, FIXTURE_SOURCE, 'utf8');

  return {
    tempRoot,
    fixtureDir,
    consumerTsPath,
    nodeModulesDir,
    symlinkPath,
  };
}

function teardownFixture(ctx: FixtureContext): void {
  rmSync(ctx.tempRoot, { recursive: true, force: true });
}

function tsconfigFor(moduleResolution: SupportedModuleResolution): string {
  const module = moduleResolution === 'NodeNext' ? 'NodeNext' : 'ESNext';
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module,
        moduleResolution,
        lib: ['ES2022'],
        types: [],
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        noEmit: true,
        isolatedModules: true,
        resolveJsonModule: true,
      },
      include: ['consumer.ts'],
    },
    null,
    2,
  );
}

function runTsc(fixtureDir: string, tsconfigName: string): {
  status: number | null;
  stdout: string;
  stderr: string;
} {
  try {
    const output = execFileSync(
      TSC,
      ['--noEmit', '-p', tsconfigName],
      { cwd: fixtureDir, stdio: 'pipe' },
    );
    return { status: 0, stdout: output.toString('utf8'), stderr: '' };
  } catch (err) {
    const e = err as NodeJS.ErrnoException & {
      status?: number | null;
      stdout?: Buffer;
      stderr?: Buffer;
    };
    return {
      status: e.status ?? null,
      stdout: e.stdout ? e.stdout.toString('utf8') : '',
      stderr: e.stderr ? e.stderr.toString('utf8') : '',
    };
  }
}

let fixture: FixtureContext | null = null;

beforeAll(() => {
  buildDeclarationsIfMissing();
  fixture = setupFixture();
});

afterAll(() => {
  if (fixture) teardownFixture(fixture);
});

describe('Phase 24H — supported-consumer assumptions (SKP-001)', () => {
  it('package devDependency pins TypeScript >= 5.4', () => {
    const pkg = JSON.parse(
      readFileSync(resolve(ROOT, 'package.json'), 'utf8'),
    ) as { devDependencies?: Record<string, unknown> };
    const tsRange = pkg.devDependencies?.typescript;
    expect(typeof tsRange).toBe('string');
    if (typeof tsRange !== 'string') return;
    const match = tsRange.match(/(\d+)\.(\d+)/);
    expect(match, `unexpected typescript range: ${tsRange}`).not.toBeNull();
    if (!match) return;
    const major = Number(match[1]);
    const minor = Number(match[2]);
    expect(major > MIN_TS_MAJOR || (major === MIN_TS_MAJOR && minor >= MIN_TS_MINOR))
      .toBe(true);
  });

  it('supported moduleResolution modes are exactly Bundler and NodeNext', () => {
    // Defensive: if a future edit drops a mode, the consumption tests
    // below stop reflecting the support contract; surface that here.
    expect([...SUPPORTED_MODULE_RESOLUTIONS].sort()).toEqual(
      ['Bundler', 'NodeNext'].sort(),
    );
  });
});

describe('Phase 24H — type-only consumption end-to-end', () => {
  it('declarations exist for both subpaths after build', () => {
    expect(existsSync(WEDGE_DTS)).toBe(true);
    expect(existsSync(HOST_DTS)).toBe(true);
  });

  it('symlinked package is reachable at node_modules/@loa/straylight', () => {
    expect(fixture).not.toBeNull();
    if (!fixture) return;
    expect(existsSync(fixture.symlinkPath)).toBe(true);
    expect(existsSync(resolve(fixture.symlinkPath, 'package.json'))).toBe(
      true,
    );
  });

  it('tsc --noEmit passes against `import type` consumption under moduleResolution=Bundler', () => {
    expect(fixture).not.toBeNull();
    if (!fixture) return;
    const tsconfigName = 'tsconfig.bundler.json';
    writeFileSync(
      resolve(fixture.fixtureDir, tsconfigName),
      tsconfigFor('Bundler'),
      'utf8',
    );
    const result = runTsc(fixture.fixtureDir, tsconfigName);
    expect(result.status, `${result.stdout}\n${result.stderr}`).toBe(0);
  });

  it('tsc --noEmit passes against `import type` consumption under moduleResolution=NodeNext', () => {
    expect(fixture).not.toBeNull();
    if (!fixture) return;
    const tsconfigName = 'tsconfig.nodenext.json';
    writeFileSync(
      resolve(fixture.fixtureDir, tsconfigName),
      tsconfigFor('NodeNext'),
      'utf8',
    );
    const result = runTsc(fixture.fixtureDir, tsconfigName);
    expect(result.status, `${result.stdout}\n${result.stderr}`).toBe(0);
  });
});

interface NodeRunResult {
  status: number | null;
  stdout: string;
  stderr: string;
}

function runNode(
  fixtureDir: string,
  fileName: string,
  extraArgs: string[] = [],
): NodeRunResult {
  try {
    const output = execFileSync(
      process.execPath,
      [...extraArgs, fileName],
      { cwd: fixtureDir, stdio: 'pipe' },
    );
    return { status: 0, stdout: output.toString('utf8'), stderr: '' };
  } catch (err) {
    const e = err as NodeJS.ErrnoException & {
      status?: number | null;
      stdout?: Buffer;
      stderr?: Buffer;
    };
    return {
      status: e.status ?? null,
      stdout: e.stdout ? e.stdout.toString('utf8') : '',
      stderr: e.stderr ? e.stderr.toString('utf8') : '',
    };
  }
}

// Phase 24H is type-only by design (SKP-001 / ADR-024G §"Decision" §2):
// the `exports` map carries no runtime condition (`default` / `import` /
// `require` / `node` / `browser` / ...). A consumer that attempts to
// resolve `@loa/straylight/host` (or `@loa/straylight`) at runtime —
// dynamic ESM `import()` or CJS `require()` — MUST fail. These tests
// pin that failure as the intended posture rather than treating it as
// a defect. They run without `npm install` and without network access:
// the symlinked `node_modules/@loa/straylight` from the positive-path
// fixture is reused.
describe('Phase 24H — runtime/value imports are unsupported by design (SKP-001)', () => {
  it('dynamic ESM `import("@loa/straylight/host")` fails to resolve', () => {
    expect(fixture).not.toBeNull();
    if (!fixture) return;
    const fileName = 'runtime-import-host.mjs';
    writeFileSync(
      resolve(fixture.fixtureDir, fileName),
      [
        '// Phase 24H negative test: dynamic ESM import of @loa/straylight/host',
        '// MUST fail because the package exports map declares no runtime',
        '// condition. The expected node error code is ERR_PACKAGE_PATH_NOT_EXPORTED.',
        "await import('@loa/straylight/host');",
        '',
      ].join('\n'),
      'utf8',
    );
    const result = runNode(fixture.fixtureDir, fileName);
    expect(
      result.status,
      `dynamic import should fail, got status=${result.status} stdout=${result.stdout} stderr=${result.stderr}`,
    ).not.toBe(0);
    expect(result.stderr).toMatch(/ERR_PACKAGE_PATH_NOT_EXPORTED/);
    // Node formats the error as: `Package subpath './host' is not defined
    // by "exports" in <path>/@loa/straylight/package.json`. Assert the
    // failure names the `./host` subpath AND the package, without
    // overconstraining the exact wording.
    expect(result.stderr).toContain("'./host'");
    expect(result.stderr).toContain('@loa/straylight');
  });

  it('CJS `require("@loa/straylight/host")` fails to resolve', () => {
    expect(fixture).not.toBeNull();
    if (!fixture) return;
    const fileName = 'runtime-require-host.cjs';
    writeFileSync(
      resolve(fixture.fixtureDir, fileName),
      [
        "// Phase 24H negative test: CJS require of @loa/straylight/host",
        '// MUST fail because the package exports map declares no runtime',
        '// condition. The expected node error code is ERR_PACKAGE_PATH_NOT_EXPORTED.',
        "require('@loa/straylight/host');",
        '',
      ].join('\n'),
      'utf8',
    );
    const result = runNode(fixture.fixtureDir, fileName);
    expect(
      result.status,
      `cjs require should fail, got status=${result.status} stdout=${result.stdout} stderr=${result.stderr}`,
    ).not.toBe(0);
    expect(result.stderr).toMatch(/ERR_PACKAGE_PATH_NOT_EXPORTED/);
    expect(result.stderr).toContain("'./host'");
    expect(result.stderr).toContain('@loa/straylight');
  });

  it('dynamic ESM `import("@loa/straylight")` (root subpath) fails to resolve', () => {
    expect(fixture).not.toBeNull();
    if (!fixture) return;
    const fileName = 'runtime-import-root.mjs';
    writeFileSync(
      resolve(fixture.fixtureDir, fileName),
      [
        '// Phase 24H negative test: even the root subpath is type-only.',
        "await import('@loa/straylight');",
        '',
      ].join('\n'),
      'utf8',
    );
    const result = runNode(fixture.fixtureDir, fileName);
    expect(
      result.status,
      `root dynamic import should fail, got status=${result.status} stdout=${result.stdout} stderr=${result.stderr}`,
    ).not.toBe(0);
    expect(result.stderr).toMatch(
      /ERR_PACKAGE_PATH_NOT_EXPORTED|ERR_MODULE_NOT_FOUND/,
    );
    expect(result.stderr).toContain('@loa/straylight');
  });

  it('CJS `require("@loa/straylight")` (root subpath) fails to resolve', () => {
    expect(fixture).not.toBeNull();
    if (!fixture) return;
    const fileName = 'runtime-require-root.cjs';
    writeFileSync(
      resolve(fixture.fixtureDir, fileName),
      [
        "// Phase 24H negative test: even the root subpath is type-only.",
        "require('@loa/straylight');",
        '',
      ].join('\n'),
      'utf8',
    );
    const result = runNode(fixture.fixtureDir, fileName);
    expect(
      result.status,
      `root cjs require should fail, got status=${result.status} stdout=${result.stdout} stderr=${result.stderr}`,
    ).not.toBe(0);
    expect(result.stderr).toMatch(
      /ERR_PACKAGE_PATH_NOT_EXPORTED|MODULE_NOT_FOUND/,
    );
    expect(result.stderr).toContain('@loa/straylight');
  });
});

// SKP-001 unsupported-resolver posture: Phase 24H supports
// `moduleResolution: "Bundler"` and `"NodeNext"` only. Older resolver
// modes (`"node"`, `"classic"`, `"node10"`, `"node16"`) are unsupported;
// a consumer using one of those modes may fail to resolve `./host`
// through the `exports.types` condition. This block exercises one
// representative unsupported mode (`"node"`, which corresponds to the
// pre-TS-5.0 default resolver and is not export-aware in the same way
// as the Bundler / NodeNext resolvers) and pins the failure mode.
describe('Phase 24H — unsupported resolver mode does not resolve `./host` (SKP-001)', () => {
  it('tsc --noEmit FAILS when moduleResolution="node" tries to resolve `@loa/straylight/host`', () => {
    expect(fixture).not.toBeNull();
    if (!fixture) return;
    const tsconfigName = 'tsconfig.legacy-node.json';
    const tsconfigBody = JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          module: 'CommonJS',
          moduleResolution: 'node',
          lib: ['ES2020'],
          types: [],
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          noEmit: true,
          isolatedModules: true,
          resolveJsonModule: true,
        },
        include: ['consumer.ts'],
      },
      null,
      2,
    );
    writeFileSync(
      resolve(fixture.fixtureDir, tsconfigName),
      tsconfigBody,
      'utf8',
    );
    const result = runTsc(fixture.fixtureDir, tsconfigName);
    // Failure is the expected, documented Phase 24H posture for
    // unsupported resolver modes. We assert non-zero status; the
    // specific TS error code may vary across TS versions but the
    // unresolved-module failure mode is stable.
    expect(
      result.status,
      `unsupported resolver mode "node" should fail to resolve @loa/straylight/host;` +
        ` got status=${result.status} stdout=${result.stdout} stderr=${result.stderr}`,
    ).not.toBe(0);
    expect(`${result.stdout}${result.stderr}`).toMatch(
      /@loa\/straylight\/host|Cannot find module|TS2307|TS2792/,
    );
  });
});
